include:
  - board: eyelash_nano
    shield: offsetkey_left 
  - board: eyelash_nano
    shield: offsetkey_right 
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_nano
    shield: settings_reset
